In [1]:
# Import the random module.
import random

In [2]:
random.randint(-90,90)

-4

In [3]:
random.random()

0.47453157222441866

In [4]:
random_number = random.randint(-90, 89) + random.random()
random_number

29.899970860337937

In [5]:
x = 1
latitudes = []
while x < 11:
    random_lat = random.randint(-90, 89) + random.random()
    latitudes.append(random_lat)
    x += 1

In [6]:
random.randrange(-90, 90, step=1)

-67

In [7]:
random.randrange(-90, 90, step=3)

-36

In [8]:
random.uniform(-90, 90)

80.47109186086462

In [9]:
# Import the NumPy module.
import numpy as np

In [10]:
np.random.uniform(-90.000, 90.000)

-64.66806103194646

In [11]:
np.random.uniform(-90.000, 90.000, size=50)

array([ 31.08067095,  64.30753474, -41.42251136,  62.98028479,
        68.46241306, -36.49110157, -14.93266476,  40.75845195,
       -70.59222585,  79.2260282 , -23.9193676 , -23.2489467 ,
        36.12532118, -62.00167607,  82.02404638,  51.4970359 ,
         1.52661145, -43.13092011,  45.64958419,  34.91790489,
        14.38144217,   0.56186687,  66.26001041, -81.77817003,
        11.87515484,  45.255402  ,  39.97038664, -62.52139513,
        68.6712165 ,  40.05139556, -49.61806704, -66.58817451,
        44.67686793,  16.27259032, -37.48275774, -83.50163539,
       -63.48639454,  67.08811008,   7.44917661,  13.47936749,
       -21.77216115, -46.16684092,  41.50278152,  55.86793243,
        84.38266375,  65.59289322,  32.11060554, -72.79150704,
        82.7495588 ,   0.69993931])

In [12]:
# Import timeit.
import timeit

In [13]:
np.random.uniform(-90.000, 90.000, size=1500)

array([ 63.69801758, -17.36099382,  -2.45058442, ...,  88.25362515,
       -28.36368968,  82.21558652])

In [14]:
%timeit np.random.uniform(-90.000, 90.000, size=1500)

15.7 µs ± 187 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [15]:
def latitudes(size):
    latitudes = []
    x = 0
    while x < (size):
        random_lat = random.randint(-90, 90) + random.random()
        latitudes.append(random_lat)
        x += 1
    return latitudes
# Call the function with 1500.
%timeit latitudes(1500)

1.6 ms ± 26.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [16]:
np.random.uniform(-90.000, 90.000, size=1500)

array([ 44.01049906, -14.32821027, -86.98205066, ..., -59.52213395,
       -79.05815363, -64.91778477])

In [17]:
%timeit np.random.uniform(-90.000, 90.000, size=1500)

15.6 µs ± 271 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
